### PR TITLE
Drop Ruby 1.8 support and add Rubies to travis

### PR DESCRIPTION
**Pull request by spk**
Follow up discussion https://github.com/bjjb/ebayr/issues/23#issuecomment-243384065

### CODE REVIEW

**Comment by spk** [comment]
Hi any release planed @bjjb ? thanks

**Comment by oehlschl** [comment]
Bump.

**Comment by bjjb** [comment]
LGTM. I'll release a new version of the gem shortly.

**Comment by bjjb** [comment]
[Released](https://rubygems.org/gems/ebayr/versions/0.0.10). Thanks, @spk .

**Pull request merged**
